### PR TITLE
Converted the .nvmrc file into a proper .node-version file and added the `engines.node` property to the package.json file

### PR DESCRIPTION
**Pull request by jonathanmarvens**
I have multiple **Node.js** versions already installed on my machine (including `v18.19.0`). Unless it’s _absolutely necessary_, I don’t want to have to install another specific version. Is there a reason why this requires `v18.17.1`?

### CODE REVIEW

**Comment by JayNakrani** [comment]
Yes, no specific reason other than the fact that it was generated using `node -v`. Is there a way to specify the minimum version to be v18.17 in nvmrc? If so, that might be better as I would love to enforce at least a min node version

**Comment by jonathanmarvens** [comment]
@JayNakrani I just pushed a commit with the necessary updates for you. I hope that helps!

**Comment by jonathanmarvens** [comment]
@JayNakrani Hey there, are you still interested in this PR? I just fixed the latest branch conflicts.

**Comment by JayNakrani** [comment]
Ah, sorry. I forgot about the PR. Thanks for resolving the merge conflict. Looks good to me.

**Pull request merged**
